name: Archive

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  archive:
    runs-on: ubuntu-latest

    env:
      BUILD: .build
      ARTIFACT: HandyNotes-Achievements
      ARCHIVE: HandyNotes-Achievements.zip

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: archive
        run: make archive

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.BUILD }}/${{ env.ARCHIVE }}
